name: Devcontainer Shellcheck

on:
  pull_request:
    paths:
      - ".devcontainer/**/*.sh"
  push:
    paths:
      - ".devcontainer/**/*.sh"

permissions:
  contents: read

jobs:
  devcontainer_shellcheck:
    name: Devcontainer Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint Devcontainer Scripts
        run: |
          find .devcontainer/ -name '*.sh' -print0 | xargs -0 shellcheck
