name: Rail Inspector

on:
  pull_request:
    paths:
    - "tools/rail_inspector/**"
  push:
    paths:
    - "tools/rail_inspector/**"

permissions:
  contents: read

jobs:
  rail_inspector:
    name: rail_inspector tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Remove Gemfile.lock
        run: rm -f Gemfile.lock
      - name: Set up Ruby
        uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
        with:
          ruby-version: 3.4
          bundler-cache: true
      - run: cd tools/rail_inspector && bundle exec rake
